mongo:
  image: mongo:latest
  command: mongod --port 27017 --dbpath /data/db --replSet rs0 --storageEngine wiredTiger
  volumes:
  - ./data/db:/data/db
  ports:
  - 27017:27017

elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
  - 9200:9200

mongo_connector:
  image: yeasy/mongo-connector:latest
  links:
  - mongo
  - elasticsearch

kibana:
  image: kibana:latest
  links:
  - elasticsearch
  ports:
  - 5601:5601
